text = input("Enter a sentence: ")
print("\nYou entered:", text)
print("\n1. Length of the string:", len(text))
print("2. Uppercase:", text.upper())
print("3. Lowercase:", text.lower())
print("4. Capitalized:", text.capitalize())
print("5. Title Case:", text.title())
print("6. Reversed String:", text[::-1])
word = input("\nEnter a word to count in the sentence: ")
print("7. Occurrence of the word:", text.count(word))
print("8. Position of the word:", text.find(word))
new_word = input("Enter a new word to replace it with: ")
print("9. After Replacement:", text.replace(word, new_word))
print("10. Is the sentence only alphabets?", text.isalpha())
print("11. Is the sentence only digits?", text.isdigit())
print("12. Words in the sentence:", text.split())
